### ISSUE TITLE
How to merge the vcfs from different samples?

### ISSUE THREAD

**Issue by verne91** [hall-lab/svtyper#102]
Hello,

I have got the svtyper results from different samples. How can I merge the vcfs into one vcf?

I found `vcf_paste.py` under scripts folder. But I don't find the usage for it.

Thank you!

**Comment by abelhj** [comment]
You can find an example workflow here.  Essentially, you will want to run svtools lsort and svtools lmerge to merge the calls across samples.  Then you can re-genotype the merge sites in all samples with svtyper, and paste the resulting vcfs together with svtools vcfpaste.

https://github.com/hall-lab/svtools/blob/master/Tutorial.md <https://github.com/hall-lab/svtools/blob/master/Tutorial.md>

Thanks,
Haley
