### ISSUE TITLE
AttributeError: 'csamtools.AlignedRead' object has no attribute 'tlen'

### ISSUE THREAD

**Issue by crazyhottommy** [hall-lab/svtyper#12]
Hi,
I am using speedseq and an error occured:

Traceback (most recent call last):
  File "/risapps/src6/speedseq//bin/svtyper", line 1044, in <module>
    sys.exit(main())
  File "/risapps/src6/speedseq//bin/svtyper", line 1036, in main
    args.debug)
  File "/risapps/src6/speedseq//bin/svtyper", line 735, in sv_genotype
    ins_hist_list[lib] = insert_hist(bam, lib_to_rg[lib])
  File "/risapps/src6/speedseq//bin/svtyper", line 658, in insert_hist
    or read.tlen <= 0
AttributeError: 'csamtools.AlignedRead' object has no attribute 'tlen'

Do you have an idea what's wrong?
Thanks!
Ming

**Comment by cc2qe** [comment]
This appears to be related to a pysam update that renamed several variables and removed backwards compatibility: http://pysam.readthedocs.org/en/latest/release.html?highlight=tlen#release-0-8-1

Could you tell me what version of pysam you're running? (The following should tell you:)
```
$ python
>>> import pkg_resources
>>> pkg_resources.get_distribution("pysam").version
'0.8.0'
```

**Comment by crazyhottommy** [comment]
`>>> import pkg_resources
>>> pkg_resources.get_distribution("pysam").version
'0.5'`

It looks like I am using 0.5

**Comment by cc2qe** [comment]
Gotcha. I think this is due to old version of pysam lacking the "tlen" tag, which was added in v0.6:

http://pysam.readthedocs.org/en/latest/release.html?highlight=tlen#release-0-6

**Comment by crazyhottommy** [comment]
it looks like starting from version 0.8.1, several variable names are changed also:
http://pysam.readthedocs.org/en/latest/release.html?highlight=tlen#release-0-8-1

**Comment by cc2qe** [comment]
yeah, although the new versions have been backward compatible with legacy variable names so I have not encountered issues with newer pysam versions

**Comment by crazyhottommy** [comment]
pysam in our HPC is updated to 0.8.3 and when I run speedseq realign, it throws me same error 
as here https://github.com/hall-lab/speedseq/issues/30

Because of this since 0.8.1? http://pysam.readthedocs.org/en/latest/release.html?highlight=tlen#release-0-8-1
```
Empty cigar now returns None (instead of [])
```
Traceback (most recent call last):
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 157, in <module>
    sys.exit(main())
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 153, in main
    args.header)
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 64, in bamtofastq
    if 5 in [x[0] for x in al.cigar]:
TypeError: 'NoneType' object is not iterable
samblaster: Version 0.1.21
samblaster: Inputting from stdin
samblaster: Outputting to stdout
samblaster: Opening temp/disc_pipe for write.
samblaster: Opening temp/spl_pipe for write.
[gzclose] buffer error
samblaster: Loaded 84 header sequence entries.
Traceback (most recent call last):
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 157, in <module>
    sys.exit(main())
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 153, in main
    args.header)
  File "/risapps/src6/speedseq//bin/bamtofastq.py", line 64, in bamtofastq
    if 5 in [x[0] for x in al.cigar]:
TypeError: 'NoneType' object is not iterable


```
[mtang1@cnode338 bin]$ /risapps/rhel6/python/2.7.6/anaconda/bin/python2.7
Python 2.7.6 |Anaconda 2.0.0 (64-bit)| (default, May 27 2014, 14:50:58) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io and https://binstar.org
>>> import pkg_resources
>>> pkg_resources.get_distribution("pysam").version
'0.8.3'
```

**Comment by cc2qe** [comment]
ah right. someone else emailed me about this issue as well. I'll try to fix it

**Comment by crazyhottommy** [comment]
appreciate that!

**Comment by woodoo46** [comment]
Is this fixed? I am still having the same problem. My pysam is 0.8.4.

**Comment by cc2qe** [comment]
this should be fixed with https://github.com/hall-lab/svtyper/commit/33db6d3d7c3bc9b5ff83978581bbabe60d5d1df9, let me know if it doesn't work now
