### ISSUE TITLE
Stopped SVtyper

### ISSUE THREAD

**Issue by sehrrot** [hall-lab/svtyper#21]
Hi,

Thanks for the nice tool. I have been running SVtyper for 1000 Genome WGS samples (~30X) after Lumpy-SV run. 

The tool worked okay when I ran with chr22. Then, I used it for entire chromosomes, and I found strange behaviour that SVTyper stopped after writing few lines (~100-200 lines including header) of VCF output. 

Then, I did bit more experiments that I did split the VCF file into few chunks (200 lines), given that the run of chr22 was okay and I assumed it could be line number issue, and ran again them but wasn't working. 

I am wondering whether you or other users noticed this issue before.

Thanks
Joon

**Comment by cc2qe** [comment]
SVtyper shouldn't stop, but it can be slow for variants where the data is very deep. Did you run LUMPY using the [exclude regions](https://github.com/hall-lab/speedseq#annotations)? also, are you able to identify the problematic variant in your VCF file?

**Comment by sehrrot** [comment]
Thanks for the feedback. I have run with exclude region options. 

I have been generating coverage using your python script (get_coverages.py). Then, should I follow the traditional usage with these coverage files? 

Also, it's ~30X WGS file and I am not sure which coverage I should use for get_exclude_regions.py. I found Lumpy-SV paper used "Any regions with depth exceeding 2 * mode + 3 standard deviations".  For this, should I use a coverage file of PE bam? or splitters bam? 

Thanks
Joon

**Comment by cc2qe** [comment]
if you're working with human genomes and GRCh37, you should probably just use the exclude regions found here: https://github.com/hall-lab/speedseq/blob/master/annotations/ceph18.b37.lumpy.exclude.2014-01-15.bed

I think get_coverages.py still works be we haven't used it in a long time.
> For this, should I use a coverage file of PE bam? or splitters bam?

if you choose to do this, then it would be a coverage of the full BAM file

**Comment by sehrrot** [comment]
Nice. Thanks. I will try both.

Good day
