### ISSUE TITLE
AttributeError: 'pysam.csamtools.AlignedRead' object has no attribute 'inferred_length'

### ISSUE THREAD

**Issue by bjkelly** [hall-lab/svtyper#37]
I was originally getting an "IndexError: list index out of range" error when using the latest release.  Now that I've updated to the latest master version, I get a "AttributeError: 'pysam.csamtools.AlignedRead' object has no attribute 'inferred_length'" error.  

I have successfully run svtyper on 10 multisample VCFs before this one.  The BAMs were all aligned and processed the same way.  There are two readgroups per BAM, one more represented than the other, but a similar ratio to previous BAMs that have not had an issue.

Based on some of the info previously requested from similar issues, I have appended some things that may be helpful:

Python 2.7.5 (default, Jul 24 2013, 15:39:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.get_distribution("pysam").version
'0.7.5'

~/apps/svtyper-master/svtyper -B BAMs/sample1.processed.bam ^C BAMs/sample1.splitreads.bam -i sample1.lumpy.vcf -n 2 -M -o sample1.lumpy.gt.vcf --debug

Traceback (most recent call last):
  File "/isilon/bgcusers/bjk003/apps/svtyper-master/svtyper", line 1418, in <module>
    sys.exit(main())
  File "/isilon/bgcusers/bjk003/apps/svtyper-master/svtyper", line 1405, in main
    args.debug)
  File "/isilon/bgcusers/bjk003/apps/svtyper-master/svtyper", line 1040, in sv_genotype
    sample = Sample.from_bam(bam_list[i], spl_bam_list[i], num_samp, min_lib_prevalence)
  File "/isilon/bgcusers/bjk003/apps/svtyper-master/svtyper", line 953, in from_bam
    new_lib = Library.from_bam(lib_name, bam, num_samp)
  File "/isilon/bgcusers/bjk003/apps/svtyper-master/svtyper", line 784, in from_bam
    num_samp)
  File "/isilon/bgcusers/bjk003/apps/svtyper-master/svtyper", line 727, in __init__
    self.calc_read_length()
  File "/isilon/bgcusers/bjk003/apps/svtyper-master/svtyper", line 809, in calc_read_length
    if read.inferred_length > max_rl:
AttributeError: 'pysam.csamtools.AlignedRead' object has no attribute 'inferred_length'

**Comment by cc2qe** [comment]
Thanks for the detailed and complete description. This is very likely to be a pysam version issue. I changed some of the variable names in conjunction with pysam version 0.8.1 updates. The ["qlen" to "inferred_length" name-change](https://github.com/hall-lab/svtyper/commit/aa9a51ee3b30f8a5e6b97669cf430ca9bc836467#diff-e732c958b2258d30fbf6fc255a4f6280R797) is what's causing this issue
http://pysam.readthedocs.io/en/latest/release.html?highlight=qlen#release-0-8-1

Updating to a pysam version >=0.8.1 should solve it

**Comment by bjkelly** [comment]
Updated to pysam-0.9.1.4 and that seemed to resolve the issue.  It's just weird that this is the first time it ran in to this issue after running it 10s of times.  But I appreciate the quick reply.  Thanks!

**Comment by aj03** [comment]
Even I am facing the same problem when running HiCExplorer software:

command:
hicBuildMatrix -s mapping/SRR1956527_1.bam mapping/SRR1956527_2.bam -rs dpnII_positions_GRCm38.bed -seq GATC -b hiCmatrix/SRR1956527_ref.bam -o hiCmatrix/SRR1956527.matrix

reading mapping/SRR1956527_1.bam and mapping/SRR1956527_2.bam to build hic_matrix
Minimum distance considered between restriction sites is 300
Max distance: 800
Matrix size: 2666241
dangling sequences to check are {'pat_forw': 'ATC', 'pat_rev': 'GAT'}
Traceback (most recent call last):
  File "/usr/local/bin/hicBuildMatrix", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/hicexplorer/hicBuildMatrix.py", line 644, in main
    mate1_supplementary_list = get_supplementary_alignment(mate1, str1)
  File "/usr/local/lib/python2.7/dist-packages/hicexplorer/hicBuildMatrix.py", line 410, in get_supplementary_alignment
    if read.has_tag('SA'):
AttributeError: 'csamtools.AlignedRead' object has no attribute 'has_tag'


pysam version:
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> pkg_resources.get_distribution("pysam").version
'0.9.1.4'

Can you please help me to solve it.
Thanks in advance
