### ISSUE TITLE
Numerical result out of range error

### ISSUE THREAD

**Issue by twieland** [hall-lab/svtyper#5]
Hi,

I'm getting an erro running svtyper:
  File "/usr/local/packages/seq/lumpy-sv/tools/svtyper/svtyper", line 964, in <genexpr>
    gt_sum = sum(10**x for x in gt_lplist)
OverflowError: (34, 'Numerical result out of range')

The entry in the VCF file that causes this error is:
chr1    17684780        42      a       <DEL>   0.00    .       TOOL=LUMPY;SVTYPE=DEL;SVLEN=-317;END=17685097;STR=+-:20;CIPOS=0,0;CIEND=0,0;EVENT=42;SUP=20;PESUP=6;SRSUP=14;EVTYPE=PE,SR;PRIN  GT:SUP:PE:SR    0/1:20:6:14

However, when I run the svtyper version that comes with speedseq I don't get the error for this entry, but for another one:
chr1    188539456       333     a       <DEL>   0.00    .       TOOL=LUMPY;SVTYPE=DEL;SVLEN=-773;END=188540229;STR=+-:155;CIPOS=0,0;CIEND=0,0;EVENT=333;SUP=155;PESUP=117;SRSUP=38;EVTYPE=PE,SR;PRIN    GT:SUP:PE:SR    0/1:155:117:38

I also noticed that the GQ is 0.00 or -0.00 for all SVs that worked.
The input VCF file was generated using the speedseq sv module. The original BAM file was aligned using bwa mem. Discordant BAM files were generated as shown on the lumpy-sv page. I used the current version of speedseq.

Best Regards,
Thomas

**Comment by cc2qe** [comment]
Hi Thomas,

can you just confirm that for the first error, you are using the most recent commit of svtyper? (https://github.com/cc2qe/svtyper/blob/fe304de3eb25f5a4cdc6b98c61ec34b9133a3cb3/svtyper) I made some updates to handle overflow recently and want to first check if those help.

The speedseq version of SVTyper is slightly behind the most recent version, so not surprised that it has different behavior

**Comment by twieland** [comment]
Hi Colby,

yes, I used the newest version. Checked it out this morning.

**Comment by cc2qe** [comment]
Ok thanks
Can you run svtyper with the --debug flag and send the  end of the output and the error message for that first variant?

You can just email it to cc2qe at virginia dot edu if you'd like
