### ISSUE TITLE
svtyper stucks

### ISSUE THREAD

**Issue by woodoo46** [hall-lab/svtyper#50]
It looks like the program gets stuck at certain point. The program stops outputting results at certain chromsome. Here is the command I used:

svtyper -B ${bamfile} -S ${splitters} -i in.vcf -M 

Did I miss any necessary input parameters?

Thanks.

**Comment by cc2qe** [comment]
Try the new version released yesterday. it should be faster and more memory efficient

**Comment by woodoo46** [comment]
Problem solved! Thanks!!!
