### ISSUE TITLE
unknown error <- the worst bug report. 

### ISSUE THREAD

**Issue by zeeev** [hall-lab/svtyper#55]
tabix -h ../ALL_Illumina_Integrate_20170206.vcf.gz chr4:140000000-150000000 | python ~/tools/svtyper/svtyper -B /net/eichler/vol24/projects/structural_variation/nobackups/bams/final/HG00512.bam,/net/eichler/vol24/projects/structural_variation/nobackups/bams/final/HG00513.bam,/net/eichler/vol24/projects/structural_variation/nobackups/bams/final/HG00514.bam,/net/eichler/vol24/projects/structural_variation/nobackups/bams/final/HG00731.bam,/net/eichler/vol24/projects/structural_variation/nobackups/bams/final/HG00732.bam,/net/eichler/vol24/projects/structural_variation/nobackups/bams/final/HG00733.bam,/net/eichler/vol24/projects/structural_variation/nobackups/bams/final/NA19238.bam,/net/eichler/vol24/projects/structural_variation/nobackups/bams/final/NA19239.bam,/net/eichler/vol24/projects/structural_variation/nobackups/bams/final/NA19240.bam -l lib.json 2> error

**error** 

Reading library metrics from lib.json...Reading library metrics from lib.json...Reading library metrics from lib.json...Reading library metrics from lib.json...Reading library metrics from lib.json...Reading library metrics from lib.json...Reading library metrics from lib.json...Reading library metrics from lib.json...Reading library metrics from lib.json... done
Traceback (most recent call last):
  File "/net/eichler/vol8/home/zevk/tools/svtyper/svtyper", line 1738, in <module>
    sys.exit(main())
  File "/net/eichler/vol8/home/zevk/tools/svtyper/svtyper", line 1733, in main
    args.alignment_outpath)
  File "/net/eichler/vol8/home/zevk/tools/svtyper/svtyper", line 1380, in sv_genotype
    vcf.add_header(header)
  File "/net/eichler/vol8/home/zevk/tools/svtyper/svtyper", line 70, in add_header
    self.add_info(*[b.split('=')[1] for b in r.findall(a)])
TypeError: add_info() takes exactly 5 arguments (4 given)

**Comment by zeeev** [comment]
Ok, just need error reporting, it's caused when SVTYPE isn't in the info field.

**Comment by cc2qe** [comment]
8637bc331085753b5a87afcd1503bd242b11eb39 throws a more informative error message if SVTYPE info field is missing
