### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ck999** [hall-lab/svtyper#8]
Hi, I am getting the following error "IndexError: list index out of range"
with the following Traceback:
Traceback (most recent call last):
  File "path_to_svtyper", line 1078, in <module>
    sys.exit(main())
  File "path_to_svtyper", line 1070, in main
    args.debug)
  File "path_to_svtyper", line 767, in sv_genotype
    sample = Sample(bam_list[i], spl_bam_list[i], num_samp)
  File "path_to_svtyper", line 734, in __init__
    self.lib_dict[name].calc_insert_hist()
  File "path_to_svtyper", line 689, in calc_insert_hist
    med = median(valueCounts)
  File "path_to_svtyper", line 567, in median
    v = valueList[i]

I used lumpyexpress to generate the vcf file, from set of bam files originally generated with bwa-mem. Samblaster was used to extract splitters. 

Thanks for any help, Chris

**Comment by cc2qe** [comment]
Hi Chris,
Can you please post your svtyper command?

**Comment by ck999** [comment]
svtyper -B a.csort.bam,b.csort.bam,c.csort.bam,d.csort.bam,e.csort.bam,f.csort.bam,g.csort.bam,h.csort.bam,i.csort.bam,j.csort.bam -S a.split.csort.bam,b.split.csort.bam,c.split.csort.bam,d.split.csort.bam,e.split.csort.bam,f.split.csort.bam,g.split.csort.bam,h.split.csort.bam,i.split.csort.bam,j.split.csort.bam -i all.lumpy.vcf > all.lumpy.gt.vcf

**Comment by ck999** [comment]
Hi Colby, 

I posted svtyper command on GitHub.

Svtyper ran successfully with a different bam/vcf combination. 

The IndexError also occurs if I generate a vcf with one sample. I.e.

svtyper -B a.csort.bam  -S a.split.csort.bam -i a.vcf > a.gt.vcf

And I get the error if I generate a vcf with a single variant. I.e. 

chrX	107013586	21	N	<DEL>	.	.	SVTYPE=DEL;STRANDS=+-:196;SVLEN=-5073;END=107018659;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=196;PE=160;SR=36	GT:SU:PE:SR	./.:0:0:0	./.:20:15:5	./.:0:0:0	./.:32:22:10	./.:0:0:0	./.:23:21:2	./.:29:26:3	./.:0:0:0	./.:38:31:7	./.:54:45:9

Thanks for the help!
Chris

**Comment by cc2qe** [comment]
thanks for the detailed bug report

It looks like SVtyper is having a problem generating an empirical histogram of insert sizes for that sample. Would you be able to send me the first 10,000 lines from that BAM (a.csort.bam)? my email is colby (dot) chiang (at) gmail

**Comment by diehlsa** [comment]
Hi,

I'm encountering the same error. Did you find out what the issue was?

I'm running SVtyper as part of the bcbio-nextgen pipeline framework with a very similar workflow as described above.

Thanks for your help,
Sarah

**Comment by cc2qe** [comment]
I never received a follow up from the earlier report, but I suspect that the BAM file might have a library that is either not present in the BAM, or at extremely low prevalence. Thus, when SVTyper builds the empirical insert size distribution from the first million reads, it finds none from that rare library and throws errors.

I've patched this bug in the latest SVTyper commit https://github.com/hall-lab/svtyper, so that might fix the problem. let me know if that helps

**Comment by chapmanb** [comment]
Colby;
Thanks for looking at this. I was going to pull in the fix to the conda package so Sarah could test but didn't see a recent commit -- is there a chance you didn't push this, or was it one of the earlier fixes? Thanks much.

**Comment by cc2qe** [comment]
The commit I was thinking of was from a few months ago (https://github.com/hall-lab/svtyper/commit/a2a9381336849d8cab5b5baa87793a0db5ebbbb4) but since it was not long before @ck999's post I thought it might be the same one. Let me know if that doesn't solve it and I'll dig further into this

**Comment by chapmanb** [comment]
Colby -- thanks much for confirming this. We were using an older version in bcbio, and I updated the conda recipe to the latest. Sarah, if you update your tools:
```
bcbio_nextgen.py upgrade --tools
```
and re-run, fingers crossed that it'll fix the issue. Thanks much for reporting this.

**Comment by diehlsa** [comment]
Thanks a lot to both of you! Due to some hardware issues I probably won't have access to my data today, but I will let you know the outcome once I can rerun it.

**Comment by diehlsa** [comment]
I finally could rerun the analysis, but I still get the same error. The svtyper version is

    __version__ = "$Revision: 0.0.4 $"
    __date__ = "$Date: 2016-04-05 09:07 $"

I checked and the BAM file does only have one read group. I asked the data owner and I can send you the first 10,000 lines of the BAM file as you asked earlier. Is there anything else I could look for? The BAM file is rather large at 106 GB. I get the error with two different samples from the same set. I started from the fastq files with the bcbio-nextgen pipeline, so the BAMs should be fine. It worked for different data run with the same pipeline version. This is the flagstat of the BAM file:

    1658145758 + 0 in total (QC-passed reads + QC-failed reads)
    18046130 + 0 secondary
    0 + 0 supplementary
    1027262547 + 0 duplicates
    1332521068 + 0 mapped (80.36%:-nan%)
    0 + 0 paired in sequencing
    0 + 0 read1
    0 + 0 read2
    0 + 0 properly paired (-nan%:-nan%)
    0 + 0 with itself and mate mapped
    0 + 0 singletons (-nan%:-nan%)
    0 + 0 with mate mapped to a different chr
    0 + 0 with mate mapped to a different chr (mapQ>=5)

**Comment by cc2qe** [comment]
thanks for the detailed info. yes, can you please send the first 10000 lines of the bam (including the header) to Colby dot Chiang at gmail? can you also paste the exact error message that you see?

**Comment by diehlsa** [comment]
Turns out I made an error in the configuration for the fastq merging and the data was regarded as single end.

Thanks again @cc2qe and @chapmanb for helping me to track down the issue and sorry for not noticing earlier that it went wrong in the very first step.
