### ISSUE TITLE
problem in running svtyper

### ISSUE THREAD

**Issue by ytguojian** [hall-lab/svtyper#81]
Hi,
Recently, I have used lumpy to call the SVs from citrus genome successfully. Then, I wanted to do the genotyping by svtyper. Here, it came some problems.  
The svtyper  can genotype successfully before it came to chromosome 7 at position around 4378666.  The output file stopped at this position. There were no error messages and the procedure was still running.
Do you know what is the problem?

Cheers,

**Comment by ernfrid** [comment]
Very exciting genome!

From your description, my best guess would be that you've hit a region of high depth and the program is stalled reading a large number of reads. I've also seen similar behavior when svtyper doesn't have enough memory allocated to it.

What version are you using and how much memory is available to the process? If you examine svtyper using `top`, is the CPU utilization high? How much memory usage is reported for the program while it is stalled?

**Comment by ytguojian** [comment]
The version is svtyper-0.0.4. Is that too old ? I will try a newer version to  do this again and will talk to you later.
Cheers,

**Comment by ernfrid** [comment]
I would definitely try the latest version. There have been many improvements since then that may help.

**Comment by ytguojian** [comment]
Hi，
Yes, It is the version problem. The  latest version is good. 
Thanks!
