### ISSUE TITLE
Can I use svtyper to genotype Hydra output?

### ISSUE THREAD

**Issue by jiangyuanluo** [hall-lab/svtyper#87]

**Comment by ernfrid** [comment]
You would need to convert Hydra output to a VCF before trying to use SVTyper. It looks like bcbio has a conversion script here: https://github.com/bcbio/bcbio-nextgen/blob/master/scripts/utils/hydra_to_vcf.py

I can't guarantee that all necessary fields are present, but it looks likely to be close to generating a suitable input file (please see #64 for a list of required fields). Note that SVTyper only operates well on one sample at a time so if you have multiple samples you will need to run SVTyper individually for each sample.
